vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /images/sportsmans
            upload_destination: '%kernel.project_dir%/public/images/sportsmans'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer