vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        athletes:  # Change this to 'athletes'
            uri_prefix: /images/athletes
            upload_destination: '%kernel.project_dir%/public/images/athletes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
